"use strict";

const crypto = require("crypto");
const fs = require("fs");
const path = require("path");
const { generateFonts } = require("fantasticon");

const root = __dirname;
const generatedDir = path.join(root, ".generated");
const publicDir = path.join(root, "..", "shell", "public", "icons");
const stylesheetPath = path.join(root, "..", "shell", "client", "styles", "_icons.scss");
const codepoints = require("./codepoints.json");
const fontTypes = ["eot", "woff2", "woff", "ttf"];

function renderStylesheet(hash) {
  const sources = [
    `url("/icons/icons-${hash}.eot?${hash}#iefix") format("embedded-opentype")`,
    `url("/icons/icons-${hash}.woff2?${hash}") format("woff2")`,
    `url("/icons/icons-${hash}.woff?${hash}") format("woff")`,
    `url("/icons/icons-${hash}.ttf?${hash}") format("truetype")`,
  ];
  const classes = Object.entries(codepoints).map(([name, codepoint]) =>
    `.icon-${name}:before {\n  content: "\\\\${codepoint.toString(16)}";\n}`).join("\n\n");

  return `// Generated by icons/build.js. Do not edit by hand.\n\n` +
    `@font-face {\n  font-family: "icons";\n` +
    `  src: url("/icons/icons-${hash}.eot?${hash}");\n` +
    `  src: ${sources.join(",\n       ")};\n` +
    `  font-weight: normal;\n  font-style: normal;\n}\n\n` +
    `.icon {\n  font-family: "icons";\n  display: inline-block;\n  line-height: 1;\n` +
    `  font-weight: normal;\n  font-style: normal;\n  speak: none;\n` +
    `  text-decoration: inherit;\n  text-transform: none;\n  text-rendering: auto;\n` +
    `  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n` +
    `// Icons\n\n${classes}\n`;
}

async function main() {
  fs.rmSync(generatedDir, { recursive: true, force: true });
  fs.mkdirSync(generatedDir, { recursive: true });
  fs.mkdirSync(publicDir, { recursive: true });

  await generateFonts({
    inputDir: root,
    outputDir: generatedDir,
    name: "icons",
    fontTypes,
    assetTypes: [],
    codepoints,
    normalize: true,
    fontHeight: 1001,
  });

  const digest = crypto.createHash("md5");
  fontTypes.forEach((type) => digest.update(fs.readFileSync(path.join(generatedDir, `icons.${type}`))));
  const hash = digest.digest("hex");

  for (const file of fs.readdirSync(publicDir)) {
    if (/^icons-[a-f0-9]+\.(eot|woff2?|ttf)$/.test(file)) {
      fs.rmSync(path.join(publicDir, file));
    }
  }

  fontTypes.forEach((type) => {
    fs.renameSync(
      path.join(generatedDir, `icons.${type}`),
      path.join(publicDir, `icons-${hash}.${type}`),
    );
  });
  fs.rmSync(generatedDir, { recursive: true, force: true });
  fs.writeFileSync(stylesheetPath, renderStylesheet(hash));
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
