#ifndef SANDSTORM_VERSION_H_
#define SANDSTORM_VERSION_H_

#ifndef SANDSTORM_CHANNEL
#define SANDSTORM_CHANNEL custom
#endif

#define SANDSTORM_STRINGIFY2(X) #X
#define SANDSTORM_STRINGIFY(X) SANDSTORM_STRINGIFY2(X)
#define SANDSTORM_CHANNEL_STR SANDSTORM_STRINGIFY(SANDSTORM_CHANNEL)

#if defined(SANDSTORM_BUILD) && SANDSTORM_BUILD > 0
#define SANDSTORM_VERSION SANDSTORM_STRINGIFY(SANDSTORM_BUILD) "-" SANDSTORM_STRINGIFY(SANDSTORM_CHANNEL)
#else
#undef SANDSTORM_BUILD
#define SANDSTORM_BUILD 0
#define SANDSTORM_VERSION "(unknown)"
#endif

#endif  // SANDSTORM_VERSION_H_
