#ifndef SANDSTORM_VERSION_H_
#define SANDSTORM_VERSION_H_

#ifndef SANDSTORM_CHANNEL
#define SANDSTORM_CHANNEL custom
#endif

#if defined(SANDSTORM_BUILD) && SANDSTORM_BUILD > 0
#define SANDSTORM_MKVERSION(BUILD, CHANNEL) #BUILD "-" #CHANNEL
#define SANDSTORM_VERSION SANDSTORM_MKVERSION(SANDSTORM_BUILD, SANDSTORM_CHANNEL)
#else
#undef SANDSTORM_BUILD
#define SANDSTORM_BUILD 0
#define SANDSTORM_VERSION "(unknown)"
#endif

#endif  // SANDSTORM_VERSION_H_
