#ifndef SANDSTORM_VERSION_H_
#define SANDSTORM_VERSION_H_

#define SANDSTORM_STRINGIFY2(X) #X
#define SANDSTORM_STRINGIFY(X) SANDSTORM_STRINGIFY2(X)

#if defined(SANDSTORM_BUILD) && SANDSTORM_BUILD > 0
#define SANDSTORM_VERSION SANDSTORM_STRINGIFY(SANDSTORM_BUILD)
#else
#undef SANDSTORM_BUILD
#define SANDSTORM_BUILD 0
#define SANDSTORM_VERSION "(unknown)"
#endif

#endif  // SANDSTORM_VERSION_H_
