name: Build and test on containers

on: 
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        builder: ["podman"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Make on Unix
        run: ./container-build.py make  CC=/usr/bin/clang CXX=/usr/bin/clang++ -d fast

