name: Build and test on containers

on: 
  workflow_dispatch:
  push:
    branches: add-container-for-ubuntu-20.04-temp

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest, mac-latest, windows-latest]
        builder: ["podman"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Prepare container
        run: ./container-build.py prepare
      - name: Make
        run: ./container-build.py make