name: node.h

on: 
  workflow_dispatch:
  push:
    branches: add-container-for-ubuntu-20.04-temp

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: printenv
        run: |
          printenv
      - name: find node.h
        run: |
          cd /
          find . -name "node.h"

