name: node.h

on: 
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: printenv
        run: |
          printenv
      - name: find node.h in runner
        run: |
          cd /home/runner/
          find . -name "node.h"
        
      - run: |
          cd /opt
          find . -name "node.h"
      - run: |
          cd /usr
          find . -name "node.h"


